apiVersion: v1
kind: Service
metadata:
  name: smart-job-tracker-backend
  labels:
    app.kubernetes.io/name: smart-job-tracker-backend
    app.kubernetes.io/part-of: smart-job-tracker
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: smart-job-tracker-backend
  ports:
    - name: http
      port: 4000
      targetPort: http
