apiVersion: v1
kind: Service
metadata:
  name: smart-job-tracker-postgres
  labels:
    app.kubernetes.io/name: smart-job-tracker-postgres
    app.kubernetes.io/part-of: smart-job-tracker
spec:
  selector:
    app.kubernetes.io/name: smart-job-tracker-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
