package com.smartjobtracker.api.error

enum class ApiErrorCode(
    val value: String,
) {
    AI_REQUEST_FAILED("AI_REQUEST_FAILED"),
    AI_RESPONSE_INVALID("AI_RESPONSE_INVALID"),
    INTERNAL_ERROR("INTERNAL_ERROR"),
    INVALID_REQUEST_PARAMETER("INVALID_REQUEST_PARAMETER"),
    JOB_NOT_FOUND("JOB_NOT_FOUND"),
    MALFORMED_REQUEST("MALFORMED_REQUEST"),
    TASK_NOT_FOUND("TASK_NOT_FOUND"),
    VALIDATION_FAILED("VALIDATION_FAILED"),
}
