package com.smartjobtracker.persistence

import jakarta.persistence.Id
import jakarta.persistence.MappedSuperclass
import jakarta.persistence.PostLoad
import jakarta.persistence.PostPersist
import jakarta.persistence.Transient
import org.springframework.data.domain.Persistable
import java.util.UUID

/**
 * Base class for entities whose id is assigned by the service rather
 * than generated by the database.
 *
 * `SimpleJpaRepository.save` chooses between `persist` and `merge` by
 * asking whether the entity is new, and its default answer is "the id is
 * null". Our ids are never null, so without this class every save takes
 * the `merge` path: a wasted `SELECT` for a row that does not exist yet,
 * and a managed copy returned instead of the caller's own instance,
 * which silently detaches anything written as
 * `repository.save(entity); return entity`.
 *
 * Implementing [Persistable] lets the entity answer for itself. The flag
 * starts out meaning "new" and is cleared once the row demonstrably
 * exists, which is true after an insert ([PostPersist]) and after a read
 * ([PostLoad]).
 *
 * The flag belongs to the object, not to the id, so a freshly
 * constructed instance carrying an existing id still reports itself as
 * new and its save fails loudly instead of overwriting the row. Update
 * the instance the repository returned; do not rebuild it.
 *
 * `@MappedSuperclass` contributes mappings to subclasses without being a
 * table itself, so this adds no column and needs no migration.
 */
@MappedSuperclass
abstract class AssignedIdEntity(
    /**
     * `@JvmField` is required, not stylistic. [Persistable] is a Java
     * interface declaring `getId()`, and Kotlin does not allow a property
     * to implement a Java interface method. Exposing the id as a plain
     * field leaves the `getId()` signature free for the override below,
     * while Kotlin call sites keep reading `entity.id` unchanged.
     */
    @Id
    @JvmField
    val id: UUID,
) : Persistable<UUID> {
    @Transient
    private var persisted: Boolean = false

    override fun getId(): UUID = id

    override fun isNew(): Boolean = !persisted

    @PostPersist
    @PostLoad
    protected fun markPersisted() {
        persisted = true
    }
}
